{% set python_min = '3.10' %}
{% set name = "birka" %}
{% set version = "0.1.3" %}

package:
  name: birka-meta

source:
  - url: https://pypi.org/packages/source/b/birka/birka-{{ version }}.tar.gz
    sha256: 5e3364e990374fadb92b6ec56ba4f14bb35328af711347461a4d4ca839934484
  - url: https://raw.githubusercontent.com/BIIFSweden/birka/v{{ version }}/resources/conda_menu_config.json
    folder: resources
    sha256: 71e278d21b3758f471b179b49b8737ed00c2089c18eabfe345dffc39ea54d1ef

build:
  number: 1

outputs:
  - name: birka
    version: {{ version }}
    build:
      noarch: python
      script: PYTHONDONTWRITEBYTECODE=1 PIP_NO_INDEX=1 PIP_IGNORE_INSTALLED=1 {{ PREFIX }}/bin/python -m pip install -vv --no-deps --no-build-isolation .
      entry_points:
        - birka = birka.__main__:main
    requirements:
      build:
        - python >=3.10,<3.12
        - python-build
        - setuptools >=64
        - setuptools-scm >=8
      host:
        - python {{ python_min }}
        - pip
        - setuptools >=64
        - setuptools-scm >=8
      run:
        - python >={{ python_min }},<3.12
        - aicsimageio
        - pandas
        - qtpy
      run_constrained:
        - lxml <5
    test:
      requires:
        - pip
        - pyside6
        - python {{ python_min }}
      imports:
        - birka
      commands:
        - pip check
    about:
      home: https://github.com/BIIFSweden/birka
      summary: A tool for bioimage data validation and archival
      license: GPL-3.0-only
      license_file: LICENSE
  - name: birka-menu
    version: {{ version }}
    build:
      noarch: python
      script:
        - mkdir -p "${PREFIX}/Menu"
        - sed "s/__PKG_VERSION__/{{ PKG_VERSION }}/" "{{ SRC_DIR }}/resources/conda_menu_config.json" > "{{ PREFIX }}/Menu/birka-menu.json"
    requirements:
      build:
        - sed  # [unix]
      run:
        - birka {{ version }}.*
    test:
      requires:
        - pyside6
        - python {{ python_min }}
      imports:
        - birka
      commands:
        - test -f "${CONDA_PREFIX}/Menu/birka-menu.json"
    about:
      home: https://github.com/BIIFSweden/birka
      summary: Menu icons for Birka
      license: GPL-3.0-only
      license_file: LICENSE

about:
  home: https://github.com/BIIFSweden/birka
  summary: A tool for bioimage data validation and archival
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  feedstock-name: birka
  recipe-maintainers:
    - jwindhager
